title: <p align="center"> Asish Sajan </p>
logo: /assets/img/Photo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/asish-p-sajan-739ab418b/">LinkedIn</a> |
  
  <br>   
      Im a Computer Vision Enthusiast.
  <br>
  </p>



theme: jekyll-theme-minimal
